### ISSUE TITLE
Create a --use-env flag for the config:generate command

### ISSUE THREAD

**Issue by okezieuc** [logchimp/logchimp-cli#96]
It will be good to have a --use-env flag for the `logchimp config:generate` command . This flag will generate logchimp.config.json from the environment variables.

I think this will make it easier for people to create the config file locally from a .env file and also when installing on a PaaS like Heroku.

@mittalyashu, what do you think about this suggestion?

**Comment by mittalyashu** [comment]
Hello @okezieuc,

Thank you for submitting your suggestions, that's a great idea to install LogChimp on service providers where we don't have direct access to VM.

Although, the question is what would be the naming convention for environment variables.

**For example:**
* `DATABASE_PORT`

Will turn into

```json 
{
	"database": {
		"port": 4000,
	}
}
``` 

What are your thoughts?

**Comment by okezieuc** [comment]
For the naming conventions, I suggest we stick with the same one used in `scripts/create-config.sh` [file](https://github.com/logchimp/logchimp/blob/master/scripts/create-config.sh) of the logchimp core repository.

Here is a list of the environment variables:
* PG_PORT
* PG_SSL
* PG_HOST
* PG_USER
* PG_DATABASE
* SERVER_PORT
* SECRET_KEY
* MAIL_PORT
* MAIL_SERVICE
* MAIL_HOST
* MAIL_USER
* MAIL_PORT

Do you feel like there is a reason to chose an alternative path in naming the variables?

**Comment by mittalyashu** [comment]
I used those names just for convenience, since it was only used for running tests in CI pipeline.

We should use descriptive names and even in future if a new integration is added it shouldn't affect existing ones.

**Comment by okezieuc** [comment]
Prefixing every environment variable with `LOGCHIMP` is certainly a great idea! I think we can go with that. So the environment variables will be something like `LOGCHIMP_PG_PORT`.

**Comment by mittalyashu** [comment]
Alright, let's go with that. 👍

**Comment by okezieuc** [comment]
Alright. Before I start, I will like to clarify some things.

When a configuration file is created with `logchimp config:generate`, the resulting JSON looks like this
```json
{
  "local": false,
  "port": 3000,
  "secretkey": "super-secret-key",
  "database": {
    ...
  },
  "mail": {
    ...
  }
}
```

which has a different structure from [the template in LogChimp's documentation](https://logchimp.codecarrot.net/docs/config).

```json
{
  "server": {
    "port": 3000,
    "secretkey": "super-secret-key",
  },
  "database": {
    ...
  },
  "mail": {
    ...
  }
}
```

Is this intentional or a bug?
Is the `local` entry needed?

I also want to know if you are fine with adding [dotenv](https://github.com/motdotla/dotenv) as a dependency. dotenv is needed to load environment variables from a `.env` file.

**Comment by mittalyashu** [comment]
It was one of the features I was working on earlier but didn't got the chance to complete it.

You can ignore that property for now.
